int _putchar(char);
char *_strcat(char *dest, char *src);
char *_strncpy(char *dest, char *src,int n);
int _strcmp(char *s1, char *s2);
void reverse_array(int *a, int n);
char *string_toupper(char *str);
char *cap_string(char *str);
char *leet(char *s);
char *rot13(char *s);
void print_number(int n);
void rev_string(char *n);
char *infinite_add(char *n1, char *n2, char *r, int size_r);
void print_line(char *c, int s, int l);
void print_butter(char *b, int size);
